### ISSUE TITLE
Odoo V14 Inotify error after pulling new source

### ISSUE THREAD

**Issue by bosd** [Tecnativa/doodba#425] opened 2021-06-04 12:33 UTC
## Odoo is not starting because of Inotify error

Odoo is unable to start.

## To Reproduce

**Affected versions**:

1. Have an working instance of doodba, perform a new img-pull and build.
```inv img-pull img-build --pull git-aggregate```
2. Odoo is unable to start ```inv start``` or docker-compose up.
3.

**Expected behavior** A clear and concise description of what you expected to happen.
To have an running odoo instance with update odoo code

**Additional context** Add any other context about the problem here. (e.g. OS, Docker
version, ...)
Odoo V14
Python3.8
Latest doodba source

See logger message
<details>

```

docker-compose -f devel.yaml up
Starting odoonode_proxy_cdnjs_cloudflare_com_1 ... done
Starting odoonode_db_1                         ... done
Starting odoonode_proxy_www_gravatar_com_1     ... done
Starting odoonode_proxy_www_google_com_1       ... done
Starting odoonode_wdb_1                        ... done
Starting odoonode_smtp_1                       ... done
Starting odoonode_proxy_fonts_gstatic_com_1    ... done
Starting odoonode_proxy_www_googleapis_com_1   ... done
Starting odoonode_proxy_fonts_googleapis_com_1 ... done
Starting odoonode_pgweb_1                      ... done
Starting odoonode_odoo_1                       ... done
Starting odoonode_odoo_proxy_1                 ... done
Attaching to odoonode_db_1, odoonode_proxy_cdnjs_cloudflare_com_1, odoonode_proxy_www_gravatar_com_1, odoonode_proxy_www_google_com_1, odoonode_proxy_fonts_gstatic_com_1, odoonode_pgweb_1, odoonode_wdb_1, odoonode_proxy_fonts_googleapis_com_1, odoonode_smtp_1, odoonode_proxy_www_googleapis_com_1, odoonode_odoo_1, odoonode_odoo_proxy_1
db_1                          | 
db_1                          | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1                          | 
db_1                          | 2021-06-04 12:13:42.195 GMT [1] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
db_1                          | 2021-06-04 12:13:42.200 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                          | 2021-06-04 12:13:42.200 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_1                          | 2021-06-04 12:13:42.241 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                          | 2021-06-04 12:13:42.303 GMT [22] LOG:  database system was shut down at 2021-06-04 12:13:30 GMT
db_1                          | 2021-06-04 12:13:42.419 GMT [1] LOG:  database system is ready to accept connections
pgweb_1                       | Pgweb v0.11.7 (git: 31f6261c1c0c7ba8bc60252da08c78a5262fdd6e) (go: go1.15.2)
pgweb_1                       | Connecting to server...
pgweb_1                       | Connected to PostgreSQL 13.1
pgweb_1                       | Checking database objects...
pgweb_1                       | Starting server...
pgweb_1                       | To view database open http://0.0.0.0:8081/ in browser
proxy_fonts_googleapis_com_1  | /usr/local/bin/proxy:21: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
proxy_fonts_googleapis_com_1  |   ip = random.choice([answer.address for answer in resolver.query(target)])
proxy_fonts_googleapis_com_1  | INFO:root:Resolved fonts.googleapis.com to 172.217.168.234
proxy_fonts_googleapis_com_1  | /usr/local/bin/proxy:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
proxy_fonts_googleapis_com_1  |   async def netcat(port):
proxy_fonts_googleapis_com_1  | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr,max-children=100 tcp-connect:172.217.168.234:80
proxy_fonts_googleapis_com_1  | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr,max-children=100 tcp-connect:172.217.168.234:443
proxy_fonts_gstatic_com_1     | /usr/local/bin/proxy:21: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
proxy_fonts_gstatic_com_1     |   ip = random.choice([answer.address for answer in resolver.query(target)])
proxy_fonts_gstatic_com_1     | INFO:root:Resolved fonts.gstatic.com to 216.58.214.3
proxy_fonts_gstatic_com_1     | /usr/local/bin/proxy:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
proxy_fonts_gstatic_com_1     |   async def netcat(port):
proxy_fonts_gstatic_com_1     | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr,max-children=100 tcp-connect:216.58.214.3:80
proxy_fonts_gstatic_com_1     | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr,max-children=100 tcp-connect:216.58.214.3:443
proxy_cdnjs_cloudflare_com_1  | /usr/local/bin/proxy:21: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
proxy_cdnjs_cloudflare_com_1  |   ip = random.choice([answer.address for answer in resolver.query(target)])
proxy_www_google_com_1        | /usr/local/bin/proxy:21: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
proxy_www_google_com_1        |   ip = random.choice([answer.address for answer in resolver.query(target)])
proxy_www_google_com_1        | INFO:root:Resolved www.google.com to 142.250.179.196
proxy_www_google_com_1        | /usr/local/bin/proxy:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
proxy_www_google_com_1        |   async def netcat(port):
proxy_www_google_com_1        | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr,max-children=100 tcp-connect:142.250.179.196:80
proxy_www_google_com_1        | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr,max-children=100 tcp-connect:142.250.179.196:443
proxy_cdnjs_cloudflare_com_1  | INFO:root:Resolved cdnjs.cloudflare.com to 104.16.18.94
proxy_cdnjs_cloudflare_com_1  | /usr/local/bin/proxy:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
proxy_cdnjs_cloudflare_com_1  |   async def netcat(port):
proxy_cdnjs_cloudflare_com_1  | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr,max-children=100 tcp-connect:104.16.18.94:80
proxy_cdnjs_cloudflare_com_1  | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr,max-children=100 tcp-connect:104.16.18.94:443
proxy_www_googleapis_com_1    | /usr/local/bin/proxy:21: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
proxy_www_googleapis_com_1    |   ip = random.choice([answer.address for answer in resolver.query(target)])
proxy_www_googleapis_com_1    | INFO:root:Resolved www.googleapis.com to 172.217.168.202
proxy_www_googleapis_com_1    | /usr/local/bin/proxy:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
proxy_www_googleapis_com_1    |   async def netcat(port):
proxy_www_googleapis_com_1    | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr,max-children=100 tcp-connect:172.217.168.202:80
proxy_www_googleapis_com_1    | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr,max-children=100 tcp-connect:172.217.168.202:443
proxy_www_gravatar_com_1      | /usr/local/bin/proxy:21: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
proxy_www_gravatar_com_1      |   ip = random.choice([answer.address for answer in resolver.query(target)])
proxy_www_gravatar_com_1      | INFO:root:Resolved www.gravatar.com to 192.0.73.2
proxy_www_gravatar_com_1      | /usr/local/bin/proxy:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
proxy_www_gravatar_com_1      |   async def netcat(port):
proxy_www_gravatar_com_1      | INFO:root:Executing: socat tcp-listen:80,fork,reuseaddr,max-children=100 tcp-connect:192.0.73.2:80
proxy_www_gravatar_com_1      | INFO:root:Executing: socat tcp-listen:443,fork,reuseaddr,max-children=100 tcp-connect:192.0.73.2:443
smtp_1                        | 2021/06/04 12:13:42 Using in-memory storage
smtp_1                        | 2021/06/04 12:13:42 [SMTP] Binding to address: 0.0.0.0:1025
smtp_1                        | 2021/06/04 12:13:42 Serving under http://0.0.0.0:8025/
smtp_1                        | [HTTP] Binding to address: 0.0.0.0:8025
smtp_1                        | Creating API v1 with WebPath: 
smtp_1                        | Creating API v2 with WebPath: 
odoo_1                        | doodba INFO: Waiting until postgres is listening at db...
odoo_proxy_1                  | /usr/local/bin/proxy:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
odoo_proxy_1                  |   async def netcat(port):
odoo_proxy_1                  | INFO:root:Executing: socat tcp-listen:6899,fork,reuseaddr,max-children=100 tcp-connect:odoo:6899
odoo_proxy_1                  | INFO:root:Executing: socat tcp-listen:8069,fork,reuseaddr,max-children=100 tcp-connect:odoo:8069
odoo_1                        | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1                        | doodba INFO: Generating /opt/odoo/auto/odoo.conf file. Overriding any existing...
odoo_1                        | doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
odoo_1                        | doodba INFO: Executing odoo --limit-memory-soft=0 --limit-time-real-cron=9999999 --limit-time-real=9999999 --workers=0 --dev=reload,qweb,werkzeug,xml
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:358: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if token is '':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:2437: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if options['min_type'] is 'min' and options['min_value'] == 0:
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:2440: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if options['max_type'] is 'max' and options['max_value'] == 0:
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:4999: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if props[i]['type'] is 'number':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:6827: SyntaxWarning: "is not" with a literal. Did you mean "!="?
odoo_1                        |   if data_bar['bar_axis_position'] is not 'none':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:6862: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if data_bar['bar_direction'] is 'left':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:6865: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if data_bar['bar_direction'] is 'right':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:6875: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if data_bar['bar_axis_position'] is 'middle':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/worksheet.py:6878: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if data_bar['bar_axis_position'] is 'none':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/chart.py:2497: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if val is 'right':
odoo_1                        | /usr/local/lib/python3.8/site-packages/xlsxwriter/chart.py:2500: SyntaxWarning: "is" with a literal. Did you mean "=="?
odoo_1                        |   if val is 'left':
odoo_1                        | 2021-06-04 12:13:49,613 1 INFO ? odoo: Odoo version 14.0 
odoo_1                        | 2021-06-04 12:13:49,614 1 INFO ? odoo: Using configuration file at /opt/odoo/auto/odoo.conf 
odoo_1                        | 2021-06-04 12:13:49,614 1 INFO ? odoo: addons paths: ['/opt/odoo/custom/src/odoo/odoo/addons', '/var/lib/odoo/addons/14.0', '/opt/odoo/auto/addons'] 
odoo_1                        | 2021-06-04 12:13:49,614 1 INFO ? odoo: database: odoo@db:5432 
odoo_1                        | 2021-06-04 12:13:50,660 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
odoo_1                        | 2021-06-04 12:13:51,350 1 INFO ? odoo.service.server: Watching addons folder /opt/odoo/custom/src/odoo/odoo/addons 
odoo_1                        | 2021-06-04 12:13:51,350 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/14.0 
odoo_1                        | 2021-06-04 12:13:51,350 1 INFO ? odoo.service.server: Watching addons folder /opt/odoo/auto/addons 
odoo_1                        | Traceback (most recent call last):
odoo_1                        |   File "/usr/local/bin/odoo", line 8, in <module>
odoo_1                        |     odoo.cli.main()
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/cli/command.py", line 61, in main
odoo_1                        |     o.run(args)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/cli/server.py", line 178, in run
odoo_1                        |     main(args)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/cli/server.py", line 172, in main
odoo_1                        |     rc = odoo.service.server.start(preload=preload, stop=stop)
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1285, in start
odoo_1                        |     watcher = FSWatcherInotify()
odoo_1                        |   File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 268, in __init__
odoo_1                        |     self.watcher = InotifyTrees(paths_to_watch, mask=INOTIFY_LISTEN_EVENTS, block_duration_s=.5)
odoo_1                        |   File "/usr/local/lib/python3.8/site-packages/inotify/adapters.py", line 372, in __init__
odoo_1                        |     self.__load_trees(paths)
odoo_1                        |   File "/usr/local/lib/python3.8/site-packages/inotify/adapters.py", line 395, in __load_trees
odoo_1                        |     self._i.add_watch(path, self._mask)
odoo_1                        |   File "/usr/local/lib/python3.8/site-packages/inotify/adapters.py", line 95, in add_watch
odoo_1                        |     wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path_bytes, mask)
odoo_1                        |   File "/usr/local/lib/python3.8/site-packages/inotify/calls.py", line 34, in _check_nonnegative
odoo_1                        |     raise InotifyError("Call failed (should not be -1): (%d)" % 
odoo_1                        | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
odoonode_odoo_1 exited with code 1
smtp_1                        | [APIv1] KEEPALIVE /api/v1/events

```
</details>

**Comment by joao-p-marques** [comment] 2021-06-04 12:35
Duplicate of https://github.com/Tecnativa/doodba/issues/329

Check the [comment with the solution](https://github.com/Tecnativa/doodba/issues/329#issuecomment-709254126)

**Closed by joao-p-marques** 2021-06-04 12:35 UTC
Labels: bug
