### ISSUE TITLE
SSL en traefik doodba

### ISSUE THREAD

**Issue by jaiodoo** [Tecnativa/doodba#303] opened 2020-04-28 14:39 UTC
Hola Jairo
Estoy montando un entorno de pruebas con doodba utilizando la versión anterior con scaffolding. El problema que tengo es que cuando me conecto al odoo que se despliega me da el error de ssl y cuando veo los logs del traefik es que no esta creando el certificado. No se bien de estos temas y quería saber si podias ayudarme porque según leo en la documentación cuando despliegas doodba el gestiona todo el tema ese de certificados.

**Comment by pedrobaeza** [comment] 2020-04-28 14:44
This repository is international, and thus it should be written in English for helping others with the same problem. Any way, you are giving 0 details about what you are doing, your scaffolding, possible log errors, so nothing can be deduced from this.

**Comment by jaiodoo** [comment] 2020-04-28 19:04
Apologize for any inconvenience it may have caused.

I went through all the steps explained to set up a test environment. I
choose the test environment because
it is the one that allows me to access it from the outside. Everything
is created fine but when I access
it the browser shows the wrong certificate alert, I can access
accepting the risks. What I wanted to know was that
if I had to have something else on the host where the containers are
running, something that the certifiers believe,
I don't know much about these issues, that's why the question is
necessary. As I read in the doodba
documentation the system deals with the issue of certificates.

**Comment by Yajo** [comment] 2020-04-29 10:30
Hi there!

Thanks for taking the time to report the problem, but **it seems like this is not exactly a bug** in this project's code and/or scope. It is more likely a problem on your specific deployment, instance or configuration.

Doodba is a project that sews many others together, such as:

- [click-odoo-contrib](https://github.com/acsone/click-odoo-contrib)
- [Copier](https://github.com/pykong/copier)
- [Docker Compose](https://docs.docker.com/compose/)
- [Docker](https://www.docker.com/)
- [Git Aggregator](https://github.com/acsone/git-aggregator)
- [Git](https://git-scm.com/)
- [Gitlab](https://gitlab.com/)
- [OCA](https://odoo-community.org/)
- [Odoo](https://www.odoo.com/)
- [Traefik](https://traefik.io)

When you use Doodba, you are expected to know those tools. Although this project includes some documentation that is specific for some of those components, we don't aim to replace their own documentation or support channels, which might be documentation, a mailing list, a chat room, a help forum, commercial support, etc.


It seems your problem is more related to Traefik.

I hope you can get proper help there. If you find out that your problem was finally caused by Doodba itself or that some if our docs are missing, incomplete, outdated or confusing, please feel free to reopen this issue, open a new one, or even contribute a PR to improve the situation.

To keep the bug tracker clean and focused, I'm going to close this issue. I hope you understand and don't take that personally. 😊

Have a nice day!

**Closed by Yajo** 2020-04-29 10:30 UTC
