### ISSUE TITLE
Partial translation of views

### ISSUE THREAD

**Issue by jans23** [Tecnativa/doodba#279] opened 2020-01-21 04:06 UTC
We are using doodba since two months to deploy our Odoo 12.0 test system (soon production system). Everything works great except a weird language issue. We use German and English languages and the issue is that German views are only partially shown in German, partially in English. This applies to standard views such as an invoice or the checkout pages in the website. Exporting the database from doodba and importing it to a local non-doodba Odoo system works and the issues doesn't appear on those. Analysing the odoo.conf and logs didn't reveal any problems. Because we are in the dark, I'm asking for pointers where to look at. Any ideas?

An example of the issue:
![Bildschirmfoto_von_2020-01-18_17-44-34](https://user-images.githubusercontent.com/1450547/72774601-78f74800-3c0b-11ea-9fcc-8fc68c203dc6.png)

**Comment by HviorForgeFlow** [comment] 2020-01-21 08:00
I assume you are running that instance on devel mode. In that case, as you are using --dev=xml for development purposes it breaks the proper use of translations.

Remove that line https://github.com/Tecnativa/doodba-scaffolding/blob/345a61e0d1092d7df989e3fc4539df5ff99fe36a/devel.yaml#L59 and test it again.

**Comment by Yajo** [comment] 2020-01-21 12:04
Possibly related to https://github.com/Tecnativa/doodba-scaffolding/pull/66.

Remember that the `devel.yaml` environment is only meant for development. If you use it in other scenarios, you're on your own. :wink:

Since this seems to be the root cause, I'm closing here. Reopen otherwise.

**Closed by Yajo** 2020-01-21 12:04 UTC

**Comment by jans23** [comment] 2020-01-21 12:05
Indeed @HviorForgeFlow 's comment solved the issue. Thank you very much for the fast response!
