### ISSUE TITLE
Addons list returns more than addons

### ISSUE THREAD

**Issue by PCatinean** [Tecnativa/doodba#179] opened 2018-11-14 17:41 UTC
Replication:
```
docker run --rm -it tecnativa/doodba:12.0 bash
> /opt/odoo/custom/src/private/oca_requirements.txt
addons list -i --private
```

**Comment by Yajo** [comment] 2018-11-15 09:23
Yikes, confirmed!

**Comment by Yajo** [comment] 2018-11-15 13:58
So this is a real bug, and the fix is in #182, but beware because that file in that folder makes no sense: OCA dependencies are expressed through `addons.yaml`, not there.

**Comment by PCatinean** [comment] 2018-11-15 14:09
Ah of course, but in my case when the CI PIPLINE builds the image I just copy the addons from the workdir of the pipline to private and install + test just private (and they happen to have oca_requirements.txt inside for runbot)

Otherwise if I aggregated the repo I'm testing and installed and tested --private --extra it would install all oca dependencies all enterprise modules and by the time the pipeline runs it could be possible that it aggregates a different version that's been pushed in the meantime. Makes sense?

**Comment by Yajo** [comment] 2018-11-16 09:02
Oh interesting, yes of course it makes sense now! :wink:

**Closed** 2018-11-16 09:02 UTC
Labels: bug
